#use_frameworks!

platform :ios, '8.0'

target 'DJCocoapods_Example' do
  pod 'DJCocoapods', :path => '../'
  pod 'AFNetworking'
  target 'DJCocoapods_Tests' do
    inherit! :search_paths

    
  end
end
